// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockencryption

import (
	"context"

	"github.com/alwitt/haven/db"
	"github.com/alwitt/haven/encryption"
	"github.com/alwitt/haven/models"
	mock "github.com/stretchr/testify/mock"
)

// NewCryptographyEngine creates a new instance of CryptographyEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCryptographyEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *CryptographyEngine {
	mock := &CryptographyEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CryptographyEngine is an autogenerated mock type for the CryptographyEngine type
type CryptographyEngine struct {
	mock.Mock
}

type CryptographyEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *CryptographyEngine) EXPECT() *CryptographyEngine_Expecter {
	return &CryptographyEngine_Expecter{mock: &_m.Mock}
}

// DecryptData provides a mock function for the type CryptographyEngine
func (_mock *CryptographyEngine) DecryptData(ctx context.Context, keyID string, encrypted encryption.EncryptedData, activeDBClient db.Database) (models.EncryptionKey, []byte, error) {
	ret := _mock.Called(ctx, keyID, encrypted, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for DecryptData")
	}

	var r0 models.EncryptionKey
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, encryption.EncryptedData, db.Database) (models.EncryptionKey, []byte, error)); ok {
		return returnFunc(ctx, keyID, encrypted, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, encryption.EncryptedData, db.Database) models.EncryptionKey); ok {
		r0 = returnFunc(ctx, keyID, encrypted, activeDBClient)
	} else {
		r0 = ret.Get(0).(models.EncryptionKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, encryption.EncryptedData, db.Database) []byte); ok {
		r1 = returnFunc(ctx, keyID, encrypted, activeDBClient)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, encryption.EncryptedData, db.Database) error); ok {
		r2 = returnFunc(ctx, keyID, encrypted, activeDBClient)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CryptographyEngine_DecryptData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptData'
type CryptographyEngine_DecryptData_Call struct {
	*mock.Call
}

// DecryptData is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - encrypted encryption.EncryptedData
//   - activeDBClient db.Database
func (_e *CryptographyEngine_Expecter) DecryptData(ctx interface{}, keyID interface{}, encrypted interface{}, activeDBClient interface{}) *CryptographyEngine_DecryptData_Call {
	return &CryptographyEngine_DecryptData_Call{Call: _e.mock.On("DecryptData", ctx, keyID, encrypted, activeDBClient)}
}

func (_c *CryptographyEngine_DecryptData_Call) Run(run func(ctx context.Context, keyID string, encrypted encryption.EncryptedData, activeDBClient db.Database)) *CryptographyEngine_DecryptData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 encryption.EncryptedData
		if args[2] != nil {
			arg2 = args[2].(encryption.EncryptedData)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CryptographyEngine_DecryptData_Call) Return(encryptionKey models.EncryptionKey, bytes []byte, err error) *CryptographyEngine_DecryptData_Call {
	_c.Call.Return(encryptionKey, bytes, err)
	return _c
}

func (_c *CryptographyEngine_DecryptData_Call) RunAndReturn(run func(ctx context.Context, keyID string, encrypted encryption.EncryptedData, activeDBClient db.Database) (models.EncryptionKey, []byte, error)) *CryptographyEngine_DecryptData_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEncryptionKey provides a mock function for the type CryptographyEngine
func (_mock *CryptographyEngine) DeleteEncryptionKey(ctx context.Context, keyID string, activeDBClient db.Database) error {
	ret := _mock.Called(ctx, keyID, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEncryptionKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) error); ok {
		r0 = returnFunc(ctx, keyID, activeDBClient)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CryptographyEngine_DeleteEncryptionKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEncryptionKey'
type CryptographyEngine_DeleteEncryptionKey_Call struct {
	*mock.Call
}

// DeleteEncryptionKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - activeDBClient db.Database
func (_e *CryptographyEngine_Expecter) DeleteEncryptionKey(ctx interface{}, keyID interface{}, activeDBClient interface{}) *CryptographyEngine_DeleteEncryptionKey_Call {
	return &CryptographyEngine_DeleteEncryptionKey_Call{Call: _e.mock.On("DeleteEncryptionKey", ctx, keyID, activeDBClient)}
}

func (_c *CryptographyEngine_DeleteEncryptionKey_Call) Run(run func(ctx context.Context, keyID string, activeDBClient db.Database)) *CryptographyEngine_DeleteEncryptionKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CryptographyEngine_DeleteEncryptionKey_Call) Return(err error) *CryptographyEngine_DeleteEncryptionKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CryptographyEngine_DeleteEncryptionKey_Call) RunAndReturn(run func(ctx context.Context, keyID string, activeDBClient db.Database) error) *CryptographyEngine_DeleteEncryptionKey_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptData provides a mock function for the type CryptographyEngine
func (_mock *CryptographyEngine) EncryptData(ctx context.Context, keyID string, plainText []byte, activeDBClient db.Database) (models.EncryptionKey, encryption.EncryptedData, error) {
	ret := _mock.Called(ctx, keyID, plainText, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for EncryptData")
	}

	var r0 models.EncryptionKey
	var r1 encryption.EncryptedData
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, db.Database) (models.EncryptionKey, encryption.EncryptedData, error)); ok {
		return returnFunc(ctx, keyID, plainText, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, db.Database) models.EncryptionKey); ok {
		r0 = returnFunc(ctx, keyID, plainText, activeDBClient)
	} else {
		r0 = ret.Get(0).(models.EncryptionKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, db.Database) encryption.EncryptedData); ok {
		r1 = returnFunc(ctx, keyID, plainText, activeDBClient)
	} else {
		r1 = ret.Get(1).(encryption.EncryptedData)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []byte, db.Database) error); ok {
		r2 = returnFunc(ctx, keyID, plainText, activeDBClient)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CryptographyEngine_EncryptData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptData'
type CryptographyEngine_EncryptData_Call struct {
	*mock.Call
}

// EncryptData is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - plainText []byte
//   - activeDBClient db.Database
func (_e *CryptographyEngine_Expecter) EncryptData(ctx interface{}, keyID interface{}, plainText interface{}, activeDBClient interface{}) *CryptographyEngine_EncryptData_Call {
	return &CryptographyEngine_EncryptData_Call{Call: _e.mock.On("EncryptData", ctx, keyID, plainText, activeDBClient)}
}

func (_c *CryptographyEngine_EncryptData_Call) Run(run func(ctx context.Context, keyID string, plainText []byte, activeDBClient db.Database)) *CryptographyEngine_EncryptData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CryptographyEngine_EncryptData_Call) Return(encryptionKey models.EncryptionKey, encryptedData encryption.EncryptedData, err error) *CryptographyEngine_EncryptData_Call {
	_c.Call.Return(encryptionKey, encryptedData, err)
	return _c
}

func (_c *CryptographyEngine_EncryptData_Call) RunAndReturn(run func(ctx context.Context, keyID string, plainText []byte, activeDBClient db.Database) (models.EncryptionKey, encryption.EncryptedData, error)) *CryptographyEngine_EncryptData_Call {
	_c.Call.Return(run)
	return _c
}

// GetEncryptionKey provides a mock function for the type CryptographyEngine
func (_mock *CryptographyEngine) GetEncryptionKey(ctx context.Context, keyID string, activeDBClient db.Database) (models.EncryptionKey, error) {
	ret := _mock.Called(ctx, keyID, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for GetEncryptionKey")
	}

	var r0 models.EncryptionKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) (models.EncryptionKey, error)); ok {
		return returnFunc(ctx, keyID, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) models.EncryptionKey); ok {
		r0 = returnFunc(ctx, keyID, activeDBClient)
	} else {
		r0 = ret.Get(0).(models.EncryptionKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, db.Database) error); ok {
		r1 = returnFunc(ctx, keyID, activeDBClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CryptographyEngine_GetEncryptionKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEncryptionKey'
type CryptographyEngine_GetEncryptionKey_Call struct {
	*mock.Call
}

// GetEncryptionKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - activeDBClient db.Database
func (_e *CryptographyEngine_Expecter) GetEncryptionKey(ctx interface{}, keyID interface{}, activeDBClient interface{}) *CryptographyEngine_GetEncryptionKey_Call {
	return &CryptographyEngine_GetEncryptionKey_Call{Call: _e.mock.On("GetEncryptionKey", ctx, keyID, activeDBClient)}
}

func (_c *CryptographyEngine_GetEncryptionKey_Call) Run(run func(ctx context.Context, keyID string, activeDBClient db.Database)) *CryptographyEngine_GetEncryptionKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CryptographyEngine_GetEncryptionKey_Call) Return(encryptionKey models.EncryptionKey, err error) *CryptographyEngine_GetEncryptionKey_Call {
	_c.Call.Return(encryptionKey, err)
	return _c
}

func (_c *CryptographyEngine_GetEncryptionKey_Call) RunAndReturn(run func(ctx context.Context, keyID string, activeDBClient db.Database) (models.EncryptionKey, error)) *CryptographyEngine_GetEncryptionKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListEncryptionKeys provides a mock function for the type CryptographyEngine
func (_mock *CryptographyEngine) ListEncryptionKeys(ctx context.Context, filters db.EncryptionKeyQueryFilter, activeDBClient db.Database) ([]models.EncryptionKey, error) {
	ret := _mock.Called(ctx, filters, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for ListEncryptionKeys")
	}

	var r0 []models.EncryptionKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.EncryptionKeyQueryFilter, db.Database) ([]models.EncryptionKey, error)); ok {
		return returnFunc(ctx, filters, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.EncryptionKeyQueryFilter, db.Database) []models.EncryptionKey); ok {
		r0 = returnFunc(ctx, filters, activeDBClient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.EncryptionKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.EncryptionKeyQueryFilter, db.Database) error); ok {
		r1 = returnFunc(ctx, filters, activeDBClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CryptographyEngine_ListEncryptionKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEncryptionKeys'
type CryptographyEngine_ListEncryptionKeys_Call struct {
	*mock.Call
}

// ListEncryptionKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - filters db.EncryptionKeyQueryFilter
//   - activeDBClient db.Database
func (_e *CryptographyEngine_Expecter) ListEncryptionKeys(ctx interface{}, filters interface{}, activeDBClient interface{}) *CryptographyEngine_ListEncryptionKeys_Call {
	return &CryptographyEngine_ListEncryptionKeys_Call{Call: _e.mock.On("ListEncryptionKeys", ctx, filters, activeDBClient)}
}

func (_c *CryptographyEngine_ListEncryptionKeys_Call) Run(run func(ctx context.Context, filters db.EncryptionKeyQueryFilter, activeDBClient db.Database)) *CryptographyEngine_ListEncryptionKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.EncryptionKeyQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.EncryptionKeyQueryFilter)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CryptographyEngine_ListEncryptionKeys_Call) Return(encryptionKeys []models.EncryptionKey, err error) *CryptographyEngine_ListEncryptionKeys_Call {
	_c.Call.Return(encryptionKeys, err)
	return _c
}

func (_c *CryptographyEngine_ListEncryptionKeys_Call) RunAndReturn(run func(ctx context.Context, filters db.EncryptionKeyQueryFilter, activeDBClient db.Database) ([]models.EncryptionKey, error)) *CryptographyEngine_ListEncryptionKeys_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEncryptionKeyActive provides a mock function for the type CryptographyEngine
func (_mock *CryptographyEngine) MarkEncryptionKeyActive(ctx context.Context, keyID string, activeDBClient db.Database) (models.EncryptionKey, error) {
	ret := _mock.Called(ctx, keyID, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for MarkEncryptionKeyActive")
	}

	var r0 models.EncryptionKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) (models.EncryptionKey, error)); ok {
		return returnFunc(ctx, keyID, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) models.EncryptionKey); ok {
		r0 = returnFunc(ctx, keyID, activeDBClient)
	} else {
		r0 = ret.Get(0).(models.EncryptionKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, db.Database) error); ok {
		r1 = returnFunc(ctx, keyID, activeDBClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CryptographyEngine_MarkEncryptionKeyActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEncryptionKeyActive'
type CryptographyEngine_MarkEncryptionKeyActive_Call struct {
	*mock.Call
}

// MarkEncryptionKeyActive is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - activeDBClient db.Database
func (_e *CryptographyEngine_Expecter) MarkEncryptionKeyActive(ctx interface{}, keyID interface{}, activeDBClient interface{}) *CryptographyEngine_MarkEncryptionKeyActive_Call {
	return &CryptographyEngine_MarkEncryptionKeyActive_Call{Call: _e.mock.On("MarkEncryptionKeyActive", ctx, keyID, activeDBClient)}
}

func (_c *CryptographyEngine_MarkEncryptionKeyActive_Call) Run(run func(ctx context.Context, keyID string, activeDBClient db.Database)) *CryptographyEngine_MarkEncryptionKeyActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CryptographyEngine_MarkEncryptionKeyActive_Call) Return(encryptionKey models.EncryptionKey, err error) *CryptographyEngine_MarkEncryptionKeyActive_Call {
	_c.Call.Return(encryptionKey, err)
	return _c
}

func (_c *CryptographyEngine_MarkEncryptionKeyActive_Call) RunAndReturn(run func(ctx context.Context, keyID string, activeDBClient db.Database) (models.EncryptionKey, error)) *CryptographyEngine_MarkEncryptionKeyActive_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEncryptionKeyInactive provides a mock function for the type CryptographyEngine
func (_mock *CryptographyEngine) MarkEncryptionKeyInactive(ctx context.Context, keyID string, activeDBClient db.Database) (models.EncryptionKey, error) {
	ret := _mock.Called(ctx, keyID, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for MarkEncryptionKeyInactive")
	}

	var r0 models.EncryptionKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) (models.EncryptionKey, error)); ok {
		return returnFunc(ctx, keyID, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) models.EncryptionKey); ok {
		r0 = returnFunc(ctx, keyID, activeDBClient)
	} else {
		r0 = ret.Get(0).(models.EncryptionKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, db.Database) error); ok {
		r1 = returnFunc(ctx, keyID, activeDBClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CryptographyEngine_MarkEncryptionKeyInactive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEncryptionKeyInactive'
type CryptographyEngine_MarkEncryptionKeyInactive_Call struct {
	*mock.Call
}

// MarkEncryptionKeyInactive is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - activeDBClient db.Database
func (_e *CryptographyEngine_Expecter) MarkEncryptionKeyInactive(ctx interface{}, keyID interface{}, activeDBClient interface{}) *CryptographyEngine_MarkEncryptionKeyInactive_Call {
	return &CryptographyEngine_MarkEncryptionKeyInactive_Call{Call: _e.mock.On("MarkEncryptionKeyInactive", ctx, keyID, activeDBClient)}
}

func (_c *CryptographyEngine_MarkEncryptionKeyInactive_Call) Run(run func(ctx context.Context, keyID string, activeDBClient db.Database)) *CryptographyEngine_MarkEncryptionKeyInactive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CryptographyEngine_MarkEncryptionKeyInactive_Call) Return(encryptionKey models.EncryptionKey, err error) *CryptographyEngine_MarkEncryptionKeyInactive_Call {
	_c.Call.Return(encryptionKey, err)
	return _c
}

func (_c *CryptographyEngine_MarkEncryptionKeyInactive_Call) RunAndReturn(run func(ctx context.Context, keyID string, activeDBClient db.Database) (models.EncryptionKey, error)) *CryptographyEngine_MarkEncryptionKeyInactive_Call {
	_c.Call.Return(run)
	return _c
}

// NewEncryptionKey provides a mock function for the type CryptographyEngine
func (_mock *CryptographyEngine) NewEncryptionKey(ctx context.Context, activeDBClient db.Database) (models.EncryptionKey, error) {
	ret := _mock.Called(ctx, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for NewEncryptionKey")
	}

	var r0 models.EncryptionKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.Database) (models.EncryptionKey, error)); ok {
		return returnFunc(ctx, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.Database) models.EncryptionKey); ok {
		r0 = returnFunc(ctx, activeDBClient)
	} else {
		r0 = ret.Get(0).(models.EncryptionKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.Database) error); ok {
		r1 = returnFunc(ctx, activeDBClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CryptographyEngine_NewEncryptionKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewEncryptionKey'
type CryptographyEngine_NewEncryptionKey_Call struct {
	*mock.Call
}

// NewEncryptionKey is a helper method to define mock.On call
//   - ctx context.Context
//   - activeDBClient db.Database
func (_e *CryptographyEngine_Expecter) NewEncryptionKey(ctx interface{}, activeDBClient interface{}) *CryptographyEngine_NewEncryptionKey_Call {
	return &CryptographyEngine_NewEncryptionKey_Call{Call: _e.mock.On("NewEncryptionKey", ctx, activeDBClient)}
}

func (_c *CryptographyEngine_NewEncryptionKey_Call) Run(run func(ctx context.Context, activeDBClient db.Database)) *CryptographyEngine_NewEncryptionKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.Database
		if args[1] != nil {
			arg1 = args[1].(db.Database)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CryptographyEngine_NewEncryptionKey_Call) Return(encryptionKey models.EncryptionKey, err error) *CryptographyEngine_NewEncryptionKey_Call {
	_c.Call.Return(encryptionKey, err)
	return _c
}

func (_c *CryptographyEngine_NewEncryptionKey_Call) RunAndReturn(run func(ctx context.Context, activeDBClient db.Database) (models.EncryptionKey, error)) *CryptographyEngine_NewEncryptionKey_Call {
	_c.Call.Return(run)
	return _c
}
