stages:
  - test

cicd:
  stage: test
  image: alwitt/cicd-support:cgoutils-0.2.0
  script:
    - go fmt $(go list ./...)
    - go vet $(go list ./...)
    - go test --count 1 -v -timeout 600s -short ./...
