// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockmaintenance

import (
	"context"

	"github.com/alwitt/haven/encryption"
	"github.com/alwitt/haven/maintenance"
	mock "github.com/stretchr/testify/mock"
)

// NewRunner creates a new instance of Runner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Runner {
	mock := &Runner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

type Runner_Expecter struct {
	mock *mock.Mock
}

func (_m *Runner) EXPECT() *Runner_Expecter {
	return &Runner_Expecter{mock: &_m.Mock}
}

// Initialize provides a mock function for the type Runner
func (_mock *Runner) Initialize(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type Runner_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Runner_Expecter) Initialize(ctx interface{}) *Runner_Initialize_Call {
	return &Runner_Initialize_Call{Call: _e.mock.On("Initialize", ctx)}
}

func (_c *Runner_Initialize_Call) Run(run func(ctx context.Context)) *Runner_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_Initialize_Call) Return(err error) *Runner_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_Initialize_Call) RunAndReturn(run func(ctx context.Context) error) *Runner_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// ListUndecryptableVersions provides a mock function for the type Runner
func (_mock *Runner) ListUndecryptableVersions(ctx context.Context) ([]maintenance.UndecryptableVersion, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUndecryptableVersions")
	}

	var r0 []maintenance.UndecryptableVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]maintenance.UndecryptableVersion, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []maintenance.UndecryptableVersion); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]maintenance.UndecryptableVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runner_ListUndecryptableVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUndecryptableVersions'
type Runner_ListUndecryptableVersions_Call struct {
	*mock.Call
}

// ListUndecryptableVersions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Runner_Expecter) ListUndecryptableVersions(ctx interface{}) *Runner_ListUndecryptableVersions_Call {
	return &Runner_ListUndecryptableVersions_Call{Call: _e.mock.On("ListUndecryptableVersions", ctx)}
}

func (_c *Runner_ListUndecryptableVersions_Call) Run(run func(ctx context.Context)) *Runner_ListUndecryptableVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_ListUndecryptableVersions_Call) Return(undecryptableVersions []maintenance.UndecryptableVersion, err error) *Runner_ListUndecryptableVersions_Call {
	_c.Call.Return(undecryptableVersions, err)
	return _c
}

func (_c *Runner_ListUndecryptableVersions_Call) RunAndReturn(run func(ctx context.Context) ([]maintenance.UndecryptableVersion, error)) *Runner_ListUndecryptableVersions_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeUndecryptableVersions provides a mock function for the type Runner
func (_mock *Runner) PurgeUndecryptableVersions(ctx context.Context) ([]maintenance.UndecryptableVersion, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PurgeUndecryptableVersions")
	}

	var r0 []maintenance.UndecryptableVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]maintenance.UndecryptableVersion, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []maintenance.UndecryptableVersion); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]maintenance.UndecryptableVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runner_PurgeUndecryptableVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeUndecryptableVersions'
type Runner_PurgeUndecryptableVersions_Call struct {
	*mock.Call
}

// PurgeUndecryptableVersions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Runner_Expecter) PurgeUndecryptableVersions(ctx interface{}) *Runner_PurgeUndecryptableVersions_Call {
	return &Runner_PurgeUndecryptableVersions_Call{Call: _e.mock.On("PurgeUndecryptableVersions", ctx)}
}

func (_c *Runner_PurgeUndecryptableVersions_Call) Run(run func(ctx context.Context)) *Runner_PurgeUndecryptableVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_PurgeUndecryptableVersions_Call) Return(undecryptableVersions []maintenance.UndecryptableVersion, err error) *Runner_PurgeUndecryptableVersions_Call {
	_c.Call.Return(undecryptableVersions, err)
	return _c
}

func (_c *Runner_PurgeUndecryptableVersions_Call) RunAndReturn(run func(ctx context.Context) ([]maintenance.UndecryptableVersion, error)) *Runner_PurgeUndecryptableVersions_Call {
	_c.Call.Return(run)
	return _c
}

// RotateEncryptionKey provides a mock function for the type Runner
func (_mock *Runner) RotateEncryptionKey(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RotateEncryptionKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_RotateEncryptionKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateEncryptionKey'
type Runner_RotateEncryptionKey_Call struct {
	*mock.Call
}

// RotateEncryptionKey is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Runner_Expecter) RotateEncryptionKey(ctx interface{}) *Runner_RotateEncryptionKey_Call {
	return &Runner_RotateEncryptionKey_Call{Call: _e.mock.On("RotateEncryptionKey", ctx)}
}

func (_c *Runner_RotateEncryptionKey_Call) Run(run func(ctx context.Context)) *Runner_RotateEncryptionKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_RotateEncryptionKey_Call) Return(err error) *Runner_RotateEncryptionKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_RotateEncryptionKey_Call) RunAndReturn(run func(ctx context.Context) error) *Runner_RotateEncryptionKey_Call {
	_c.Call.Return(run)
	return _c
}

// RotateKEK provides a mock function for the type Runner
func (_mock *Runner) RotateKEK(ctx context.Context, newKEK encryption.KEKParams) error {
	ret := _mock.Called(ctx, newKEK)

	if len(ret) == 0 {
		panic("no return value specified for RotateKEK")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, encryption.KEKParams) error); ok {
		r0 = returnFunc(ctx, newKEK)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Runner_RotateKEK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateKEK'
type Runner_RotateKEK_Call struct {
	*mock.Call
}

// RotateKEK is a helper method to define mock.On call
//   - ctx context.Context
//   - newKEK encryption.KEKParams
func (_e *Runner_Expecter) RotateKEK(ctx interface{}, newKEK interface{}) *Runner_RotateKEK_Call {
	return &Runner_RotateKEK_Call{Call: _e.mock.On("RotateKEK", ctx, newKEK)}
}

func (_c *Runner_RotateKEK_Call) Run(run func(ctx context.Context, newKEK encryption.KEKParams)) *Runner_RotateKEK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 encryption.KEKParams
		if args[1] != nil {
			arg1 = args[1].(encryption.KEKParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runner_RotateKEK_Call) Return(err error) *Runner_RotateKEK_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Runner_RotateKEK_Call) RunAndReturn(run func(ctx context.Context, newKEK encryption.KEKParams) error) *Runner_RotateKEK_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type Runner
func (_mock *Runner) Status(ctx context.Context) (maintenance.Status, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 maintenance.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (maintenance.Status, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) maintenance.Status); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(maintenance.Status)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runner_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type Runner_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Runner_Expecter) Status(ctx interface{}) *Runner_Status_Call {
	return &Runner_Status_Call{Call: _e.mock.On("Status", ctx)}
}

func (_c *Runner_Status_Call) Run(run func(ctx context.Context)) *Runner_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_Status_Call) Return(status maintenance.Status, err error) *Runner_Status_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *Runner_Status_Call) RunAndReturn(run func(ctx context.Context) (maintenance.Status, error)) *Runner_Status_Call {
	_c.Call.Return(run)
	return _c
}
